# Generated by Django 4.0.5 on 2022-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPfinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=40)),
                ('mes', models.CharField(max_length=40)),
                ('año', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite', models.IntegerField(choices=[[1, 'Apostilla'], [2, 'Partidas'], [3, 'Residencia Uruguaya'], [4, 'Titulos de Estudio'], [5, 'DNI'], [6, 'Pasaporte'], [7, 'Turnos visados'], [8, 'Otro']], verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='ModeloTipodeTramite',
        ),
    ]
